### ISSUE TITLE
Broken test with flake8>=3.9.1

### ISSUE THREAD

**Issue by mweinelt** [PyCQA/pep8-naming#171]
After upgrading to flake>=3.9.1 the following test failure came up.

```
Traceback (most recent call last):
  File "run_tests.py", line 117, in <module>
    main()
  File "run_tests.py", line 34, in main
    errors += test_file(filename, testcase, code, options)
  File "run_tests.py", line 99, in test_file
    parse_options(checker, options)
  File "run_tests.py", line 90, in parse_options
    checker.parse_options(processed_options)
  File "/nix/store/9fggrr07qvlrqqqf2lpy9ynfn30v1ans-python3.8-pep8-naming-0.11.1/lib/python3.8/site-packages/pep8ext_naming.py", line 181, in parse_options
    engine = style_guide.DecisionEngine(options)
  File "/nix/store/mr2dci4kaf4illh63hb264lhn4vp6s1w-python3.8-flake8-3.9.1/lib/python3.8/site-packages/flake8/style_guide.py", line 171, in __init__
    ).union(options.extended_default_ignore)
AttributeError: 'Values' object has no attribute 'extended_default_ignore'
```

Seems related to this change: https://github.com/PyCQA/flake8/pull/1317

**Comment by sigmavirus24** [comment]
I suspect we didn't cut a new release that includes the updates to our test suite yet @jparise ?

**Comment by jparise** [comment]
Our usage of `extend_default_ignore` was introduced in b562e5a, which has yet to be released in a tagged version. I can do that soon.

... but that doesn't explain the error above, which is for the tagged 0.11.1 release. Is there something backwards-incompatible about flake8's 3.9.1's "extended ignore" implementation?

**Comment by sigmavirus24** [comment]
I believe our tests mock out things that are internal to Flake8, which I've never liked but it hasn't caused too much trouble. I think the change I made caused those half-mocked things to not have all the detail needed

**Comment by sigmavirus24** [comment]
https://github.com/PyCQA/pep8-naming/pull/157/commits/6d62db81d7967e123e29673a4796fefec6f06d26 is (I believe) what would fix things

**Comment by jparise** [comment]
I believe this was fixed in the last release. Can you confirm, @mweinelt?

**Comment by mweinelt** [comment]
Yes, LGTM. Thanks!
